### ISSUE TITLE
How to convert MERLIN outputs into a phylogeny

### ISSUE THREAD

**Issue by teng-gao** [raphael-group/MERLIN#6]
Hi, 

How do I get a single-cell phylogeny (e.g. in Newick format) from the output matrices?

Thanks,
Teng

**Comment by ViolaChenYT** [comment]
hi! I added a script in /src/ called A_matrix_to_newick.py, the A matrix is the output from original merlin script
this gives a cell lineage tree (not necessarily binary) where the leaves are cell names
hope this helps
